# Generated by Django 5.0.4 on 2024-04-21 18:19

import django.db.models.deletion
import products.helps
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to=products.helps.SaveMediaFile.category_image_path)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customers')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('manufacturer_name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to=products.helps.SaveMediaFile.product_image_path)),
                ('price', models.FloatField()),
                ('price_type', models.CharField(choices=[("so'm", "so'm"), ('$', '$')], default='$', max_length=10)),
                ('rating', models.FloatField(default=0)),
                ('max_weight', models.FloatField(default=0)),
                ('max_weight_type', models.CharField(choices=[('g', 'g'), ('kg', 'kg'), ('t', 't')], default='kg', max_length=10)),
                ('min_weight', models.FloatField(default=0)),
                ('min_weight_type', models.CharField(choices=[('g', 'g'), ('kg', 'kg'), ('t', 't')], default='kg', max_length=10)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.category')),
                ('comments', models.ManyToManyField(blank=True, null=True, to='products.comment')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_number', models.IntegerField(default=1)),
                ('shipping_price', models.FloatField(default=3)),
                ('total_price', models.FloatField(default=0)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
    ]
